### ISSUE TITLE
KafkaReceiver stuck in a loop of Scheduler unavailable after exception 

### ISSUE THREAD

**Issue by MarekChodak** [reactor/reactor-kafka#123]
Sorry if this a wrong place to ask.
We are experiencing an issue with KafkaReceiver. After there is a exception somewhere in the receiver pipeline and we specify retry() it tries to rebuild the KafkaReceiver. It connects to Kafka but when it tries to produce the message there is an exception 

reactor.core.Exceptions$StaticRejectedExecutionException: Scheduler unavailable

Then it fails tries to rebuild again and its stuck in this loop. I tried using an example from this repo in the SampleScenarios.

    return KafkaReceiver.create(receiverOptions(Collections.singletonList(topic)).commitInterval(Duration.ZERO))
                           .receive()
                           .publishOn(scheduler)
                           .concatMap(m -> storeInDB(m.value())
                                          .thenEmpty(m.receiverOffset().commit()))
                           .retry()
                           .doOnCancel(() -> close());

Tried using different Schedulers but no success. Also tried not disposing them on cancelation.

What we try to achieve is that our message is only committed if there is not error and if error happens its going to keep trying to process it until it succeeds.

## Expected Behavior
KafkaReceiver rebuilds and process the message again

## Actual Behavior
KafkaReceiver is stuck in a failing loop

## Steps to Reproduce
Using the KafkaSource SampleScenario from this repository and force error on mapping step

**Comment by ginkel** [comment]
@MarekChodak Have you been able to work around this issue? I am regularly seeing this error in production and like to come up with a fix...

**Comment by MarekChodak** [comment]
@ginkel No, we decided to switch to standard Kafka client as we decided that this was too risky for us

**Comment by aviscasillas** [comment]
@MarekChodak @ginkel 

Just in case it could be useful to you, I've just landed into this issue experiencing exactly the same problem, and I've finally realised that the `SampleConsumer` (https://github.com/reactor/reactor-kafka/blob/master/reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleConsumer.java#L80) was processing the records within the subscribe lambda, so in the end I've used the `receiveAutoAck` method, and handled the retries on top of the given Flux (my code is in Kotlin, but the idea is basically the same):

```
kafkaReceiver.receiveAutoAck().subscribe { recordsFlux ->
    recordsFlux
        .doOnNext { record -> process(record) }
        .doOnError { e -> logError(e.message) }
        .retryBackoff(1_000_000, Duration.ofSeconds(2))
        .subscribe()
}
```

Note that I could use the `receiveAutoAck` method, because the "commit all or nothing" approach fit's well enough in my use case. 

I didn't check the single record commit approach, but I would start looking into a similar direction by wrapping the record within a `Mono`:

```
kafkaReceiver.receive().subscribe { record ->
    Mono.just(record)
        .doOnNext { record -> process(record) }
        .doOnNext { record -> record.receiverOffset().acknowledge }
        .doOnError { e -> logError(e.message) }
        .retryBackoff(1_000_000, Duration.ofSeconds(2))
        .subscribe()
}
```

I'm also not 100% sure if that's the proper way to solve the problem, but it initially seems to be working for me.

I hope it somehow helped 😊 .

**Comment by aviscasillas** [comment]
Sorry let me correct my finding:

The problem was just about performing the retry on top of the main chain. It's ok by just doing it within the `concatMap` and subscribe only on to the main chain 😅 :
```
kafkaReceiver.receiveAutoAck()
    .concatMap { recordsFlux ->
        recordsFlux
            .doOnNext { record -> process(record) }
            .doOnError { e -> logError(e.message) }
            .retryBackoff(1_000_000, Duration.ofSeconds(2))
    }
    .subscribe()
```

**Comment by ginkel** [comment]
Thanks, @aviscasillas! BTW, I was wondering whether this problem may also be fixed with https://github.com/reactor/reactor-kafka/commit/bc13942ab372218fd83d038943e61612e503c095.

**Comment by bsideup** [comment]
@ginkel there were a few fixes that should have fixed this.
Consider trying the latest snapshots or wait for the first milestone release 👍

**Comment by AlexeiZenin** [comment]
Still seeing this. Is there anyway the KafkaConsumer could not disconnect from the Kafka cluster and create a totally brand new instance (it is expensive to do so and causes tonnes of unnecessary group rebalances when you could just poll() again to send the records that failed like the spring-kafka team does with their error handling)?

**Comment by SentryMan** [comment]
I'm also seeing this issue, but for only one of my consumers

**Comment by vickumar1981** [comment]
An example would be really nice - possibly one that works with Spring's WebFlux.

My current code looks like this:

```
Flux.defer(listener::receive)
        .map(IncomingMessage::of)
        .publishOn(scheduler)
        .concatMap(
            msg ->
                processMessage(msg)
                    .retryBackoff(
                        retryProps.getMaxRetries(),
                        Duration.ofSeconds(retryProps.getFirstBackoff()),
                        Duration.ofSeconds(retryProps.getMaxBackoff()),
                        retryProps.getJitter())
                    .doOnError(
                        IllegalStateException.class,
                        ise -> {
                          Try.of(() -> (RetryProcessingError) ise.getCause())
                              .flatMap(
                                  rpe -> {
                                    ErrorLogMessage errorLogMessage =
                                        ErrorLogMessage.builder()
                                            .errorData(rpe.getMessage())
                                            .build();
                                    errorLogService.sendError(errorLogMessage);
                                    return safeCommit(rpe.getOffset());
                                  })
                              .onFailure(
                                  e -> log.error(ise.getCause().getMessage(), ise.getCause()));
                        }))
        .subscribe(
            v -> log.info("DONE SUBSCRIBING TO KAFKA"),
            e -> log.error("ERROR WITH KAFKA RECEIVER"))
```

successful messages work fine and commit, but the retry does cause a new consumer.  also, when the retries are exhausted, then the kafka receiver stops getting new messages.

not sure what the best approach is.  any help appreciated.  thansk.

**Comment by SentryMan** [comment]
I managed to resolve it for my project by handling all my errors and retrying inside the processing flatmap. I believe propagating error signals and retrying directly on the recordflux caused the issue.

**Comment by karthekean-rgb** [comment]
@SentryMan Would you be able to point some handling on your code. I'm struck with a similar situation.

**Comment by SentryMan** [comment]
> @SentryMan Would you be able to point some handling on your code. I'm struck with a similar situation.

My code looks something like this, the errors should be handled in the flatmap function.
```java
kafkaReceiver.receiveAutoAck()
    .concatMap( recordFlux ->  recordFlux)
  //processing and errorhandling should happen in the flatmap
    .flatMap(this::processRecord)
    .subscribe()
```
in the processing funtion, you can do whatever you want, as long as any error signals are handled by a recovery operator.
```java
processRecord(ConsumerRecord<String, String> record){
return Mono.just(record)
            .map(service::doSomething)
            .flatMap(service::doSomethingelse)
            .retry(3)
           // Now error signals won't propagate to the kafkaReciever
            .onErrorResume(ex->Mono.empty());
}
```

**Comment by karthekean-rgb** [comment]
@SentryMan Thanks for sharing out  ! Looks like this is using AutoAck as well.. I figured out something similar using doOnNext by handling exceptions within the child flux but wanted to see if this can work on receive without auto ack where it passes the commit control to us.

**Comment by bsideup** [comment]
1.3.0 is released now and comes with reworked internals. @MarekChodak could you please try it?

**Comment by karthekean-rgb** [comment]
@bsideup switching over to 1.3.0 caused this `Failed to instantiate [reactor.kafka.sender.KafkaSender]: Factory method 'kafkaSender' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/core/publisher/Sinks$EmitFailureHandler` leading app to be not starting up. io.reactivex.rxjava3:rxkotlin:3.0.0 and org.reactivestreams:reactive-streams:1.0.3 are some of my other dependencies

**Comment by bsideup** [comment]
@karthekean-rgb 1.3.0 depends on reactor-core 3.4.0, make sure that you're not overriding it

**Comment by karthekean-rgb** [comment]
> @karthekean-rgb 1.3.0 depends on reactor-core 3.4.0, make sure that you're not overriding it

Ahh I was just attempting the same which made the app work and was about to edit my findings . Thank you @bsideup  !

**Comment by karthekean-rgb** [comment]
Also another update ! with 1.3.0 This issue of scheduler being unavailable upon any exception appears to be resolved and the app works fine with retry mechanism. The consumer gets closed though and I have a mechanism to restart that using doFinally in case of any unexpected exception. Thank you @bsideup

**Comment by bsideup** [comment]
This sounds like the correct behaviour according to reactive streams - any error would cancel upstream.
`onErrorResume` inside processing `flatMap`/`concatMap` can be used to handle the error gracefully.

**Comment by magro** [comment]
I just found this when looking for proper error handling with reactor kafka. What would be a proposed solution for 1.3.x, as a code sample?

**Comment by karthekean-rgb** [comment]
kafkaReceiver.receive().publishOn(//set schedulers)
.flatMap { r->
   customProcess(//ack / commit here)
        .retryWhen( // custom retry)
        .onErrorResume(//custom retry)
        
        
}.doFinally{}
.subscribe()
}
This should be the high level sample with manual commits using flatmap and a retry block.

**Comment by kharel** [comment]
I have tried this solution.
I put the retry() inside the flatmap and outside the flatmap. Same result - Scheduler unavailable exception
Any other suggestion?
